var whitelist = new Array();
whitelist = [
	//[search strings, display name, typewolf link]
	["apercu", "Apercu", "apercu"],
	["futura", "Futura", "futura"],
	["gt america", "GT America", "gt-america"],
	["dia", "Dia", "dia"],
	["domaine text", "Domaine Text", "domaine-text"],
	["domainetext", "Domaine Text", "domaine-text"],
	["domainedisplaynarrow", "Domaine Display", "domaine-display"],
	["nyt-cheltenham", "Cheltenham", "cheltenham"]
];


//Change to 1 to display popularity in tooltip
displayPopularity = 0; 

//These strings are font-family names
//When there the cursor rolls over an exact match, a number will appear in the tooltip 
//corresponding to its place in the array
var popularFonts = new Array();
popularFonts = [
	"Open Sans",
	"Lato",
	"Whitney ScreenSmart",
	"Proxima Nova",
	"Gotham Narrow SSm",
	"Source Sans Pro",
	"Roboto",
	"Gotham ScreenSmart",
	"Raleway",
	"Montserrat",
	"Brandon Grotesque",
	"Freight Text Pro",
	"Gotham",
	"proxima-nova",
	"Futura PT",
	"Avenir",
	"Merriweather",
	"Leitura News",
	"Rooney Sans Web",
	"JAF Bernino Sans",
	"Myriad Pro",
	"PT Sans",
	"Lucida Sans Unicode",
	"Trebuchet MS",
	"Apercu Regular",
	"Varela Round",
	"Oswald",
	"nyt-cheltenham",
	"ProximaNova",
	"PT Serif",
	"Sentinel ScreenSmart",
	"Droid Sans",
	"FF Meta Serif Web Pro",
	"Roboto Slab",
	"Libre Baskerville",
	"Hiragino Kaku Gothic Pro",
	"Roboto Condensed",
	"ãƒ¡ã‚¤ãƒªã‚ª",
	"Playfair Display",
	"adobe-clean",
	"MS PGothic",
	"RobotoDraft",
	"Avenir Next",
	"Avenir W01",
	"Museo Sans",
	"Founders-Grotesk",
	"futura-pt",
	"Minion Pro",
	"adelle",
	"Atlas Grotesk Web",
	"FF Tisa Pro",
	"favoritwarp",
	"Proxima Nova Regular",
	"Whitney",
	"Adobe Garamond Pro",
	"Freight Sans Pro",
	"Droid Serif",
	"Mercury Text ScreenSmart",
	"sqmarket",
	"Karla",
	"Maison Neue for TGD",
	"Interstate",
	"MuseoSans",
	"Myriad Set Pro",
	"Noto Sans",
	"Adelle Sans",
	"RooneySans-Regular",
	"Segoe UI",
	"TiemposText",
	"Georgia Pro",
	"open sans",
	"Asap",
	"Ubuntu",
	"Adobe Garamond W08",
	"Cabin",
	"Calibri",
	"f37_ginger_bold",
	"nyt-cheltenham-hinted",
	"rooney-sans",
	"Lasiver-Light",
	"Monaco",
	"Verlag",
	"brandon-grotesque",
	"Sentinel",
	"TWC Round WS",
	"ãƒ’ãƒ©ã‚®ãƒŽè§’ã‚´ Pro W3",
	"Apercu Bold",
	"Chaparral Pro",
	"FontAwesome",
	"HUGEAvantGardeBold",
	"nta",
	"open_sansregular",
	"Lora",
	"Abril Fatface",
	"Adelle",
	"Fakt",
	"freight-text-pro",
	"Balto",
	"Brioni"
];
